server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers, RETAIN_FIRST
          routes:

            - id: employee-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/employees/**

            - id: skill-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/skills/**

            - id: assessment-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/assessments/**

            - id: competency-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/competency/**

            - id: certification-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/certifications/**

            - id: learning-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/learning/**

            - id: career-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/career/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
